# This file should contain everything to configure the workflow on a global scale.
# In case of sample based data, it should be complemented by a samples.tsv file that contains
# one row per sample. It can be parsed easily via pandas.
#

#adapters file for usage to allow trimming to take place 
#These adapters are specific to the type of sequencing that was performed
#Trimming is not necessary if you end up changing the aligner to bowtie 2 which performs soft clipping
ADAPTERS: "/home/groups/MaxsonLab/callahro/adapters/nextera_adapters.fasta" 


##############################################################################
# Genome and project-specific files that will change from project-to-project
##############################################################################

# GTF file for the genome build you would like to use

gtf_file:
  /home/groups/CEDAR/tools/cfRNA_resources/gencode.v27.annotation.gtf

# Pre-built star indexes for hg38
star_index:
  /home/groups/CEDAR/roskamsh/tools/cfRNA_star_index

#this is used by te transcripts to decide where the TE are
genome:
  /home/groups/CEDAR/tools/cfRNA_resources/GRCh38.primary_assembly.genome.fa

####################################################################
# Tool-specific files that will not change from project-to-project
####################################################################

# Pre-built genome indexes for various organisms which we will screen against to look for contamination
conf:
  /home/groups/CEDAR/tools/FastQ_Screen_Genomes/fastq_screen.conf
# Paths to various tools which are used in this pipeline
star_tool:
  /home/exacloud/lustre1/CEDAR/tools/STAR/tags/2.5.3a/bin/Linux_x86_64/STAR
sickle_tool:
  /home/groups/CEDAR/tools/sickle
picard_tool:
  /home/groups/CEDAR/tools/picard-tools-1.119/MarkDuplicates.jar
bamstats_tool:
  /home/groups/CEDAR/roskamsh/tools/bamstats_bin/bamstats

##########################################
# Important project-specific paths/files
##########################################

# Metadata needed for differential expression analysis
omic_meta_data:
  #/home/groups/CEDAR/callahro/projects/outside_cfRNA_data/cfRNA-seq-pipeline/yu_fastq_list_better_groups.txt 

#############################################################################################
# Project-specific specifications you will need to make prior to submission of the pipeline
#############################################################################################
project_id:
  "microbial_read_analysis"
#
